### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by koji** [koji/icTrainer#17]
```
pip install ictrainer --user
Collecting ictrainer
  Using cached https://files.pythonhosted.org/packages/c9/79/89690f99a237a5472f1476ac8df23f040151e3ef309ecfe837bfb24fc222/ictrainer-0.2.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cail4vjx/ictrainer/setup.py", line 6, in <module>
        long_description=open('readme.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cail4vjx/ictrainer/
```

**Comment by koji** [comment]
solved by version 0.2.7
